export const INTRO_HOOKS = [
  "Analisei {X} posts e descobri algo surpreendente.",
  "95% dos profissionais cometem esse erro no LinkedIn.",
  "Isso mudou minha carreira para sempre.",
  "Passei 3 anos aprendendo isso da pior forma.",
  "O que ninguém te conta sobre {X}.",
  "Recebi {X} mensagens depois de postar isso.",
  "Demiti meu melhor funcionário. Vou te contar por quê.",
  "Perdi R$ {X} antes de entender isso.",
  "Estudei os top 1% de {X}. Aqui está o padrão.",
  "Isso vai contra tudo que te ensinaram sobre {X}.",
  "Cometi esse erro por 5 anos. Você também comete?",
  "Li 47 livros sobre {X}. Aqui está o resumo.",
  "Entrevistei 100 {X}. Descobri um padrão.",
  "Essa pergunta mudou minha visão sobre {X}.",
  "Abandonei {X} e minha vida mudou.",
  "Trabalhei 15 horas por dia. Foi um erro.",
  "Meu maior fracasso virou minha maior lição.",
  "Parei de fazer {X}. Os resultados foram imediatos.",
  "Isso vale mais que um MBA.",
  "A verdade sobre {X} que poucos falam.",
  "Fiz {X} por 10 anos. Estava errado.",
  "Um cliente me ensinou mais que qualquer curso.",
  "Essa conversa de 5 minutos mudou tudo.",
  "Deixei de ganhar {X} por não saber isso antes.",
  "O segredo está nos detalhes que ignoramos.",
  "Testei 50 estratégias. Só 3 funcionaram.",
  "Isso parece óbvio, mas quase ninguém faz.",
  "A lição mais cara que já paguei.",
  "Por que os melhores fazem diferente?",
  "Descobri isso aos 40. Queria ter sabido aos 20.",
  "Meu mentor me disse algo que nunca esqueci.",
  "Esse número mudou minha perspectiva.",
  "A pergunta que todo {X} deveria fazer.",
  "Isso não está nos livros de {X}.",
  "Passei 6 meses estudando. O resultado?",
  "A diferença entre bons e excelentes profissionais.",
  "Isso me custou 2 anos de atraso na carreira.",
  "A verdade incômoda sobre {X}.",
  "Parei de seguir conselhos tradicionais.",
  "O que aprendi errando mais que acertando.",
  "Essa decisão me assustava. Tomei mesmo assim.",
  "Você está fazendo {X} do jeito errado.",
  "Isso parece contraintuitivo, mas funciona.",
  "A estratégia que dobrou meus resultados.",
  "Por que 90% das pessoas não conseguem {X}?",
  "O método que mudou minha produtividade.",
  "Isso deveria ser ensinado na faculdade.",
  "A resposta estava na minha frente o tempo todo.",
  "Por que os melhores não seguem a maioria?",
  "Minha jornada de {X} para {Y}.",
  "Isso destruiu uma crença que eu tinha há anos.",
  "O que os dados revelam sobre {X}.",
  "Antes disso, eu estava completamente perdido.",
  "A habilidade mais subestimada do mercado.",
  "Por que talento não é suficiente?",
  "O dia que tudo mudou para mim.",
  "Essa prática simples mudou minha manhã.",
  "O erro que quase arruinou meu negócio.",
  "Por que os melhores parecem ter mais tempo?",
  "A mentalidade que me desbloqueou.",
  "Isso vai parecer estranho, mas funciona.",
  "O conselho que recebi e ignorei por anos.",
  "Por que você deveria parar de fazer {X}?",
  "O que ninguém te avisa antes de {X}.",
  "Essa técnica triplicou meu engajamento.",
  "A pergunta que todo líder deveria fazer.",
  "Por que complicamos o que é simples?",
  "O padrão que observei em pessoas bem-sucedidas.",
  "Isso me fez repensar minha estratégia.",
  "A decisão mais difícil da minha carreira.",
  "Por que velocidade nem sempre é a resposta?",
  "O framework que uso há 5 anos.",
  "Isso vai mudar como você vê {X}.",
  "A regra que nunca quebro.",
  "Por que a maioria para no meio do caminho?",
  "O insight que veio de onde menos esperava.",
  "Isso me custou caro, mas valeu a pena.",
  "A mudança que fez toda a diferença.",
  "Por que menos pode ser mais em {X}?",
  "O momento de virada foi este.",
  "Isso me fez questionar tudo que sabia.",
  "A estratégia contraintuitiva que funciona.",
  "Por que os melhores são obcecados por {X}?",
  "O erro mais comum em {X}.",
  "Isso não é sobre trabalhar mais.",
  "A lição que aprendi da forma mais difícil.",
  "Por que você deveria investir em {X}?",
  "O que mudou quando parei de {X}.",
  "Isso me levou de {X} para {Y}.",
  "A verdade sobre sucesso no LinkedIn.",
  "Por que a consistência vence o talento?",
  "O segredo que descobri por acaso.",
  "Isso me fez mais produtivo em 30 dias.",
  "A habilidade que todo profissional precisa.",
  "Por que os iniciantes têm vantagem?",
  "O que acontece quando você para de {X}?",
  "Isso vai te poupar anos de erro.",
  "A mentalidade de quem alcança resultados.",
];

export const VIRAL_HOOKS = [
  "Isso vai ser polêmico, mas precisa ser dito.",
  "A maioria vai discordar. E tudo bem.",
  "Prepare-se para mudar de opinião.",
  "Isso me rendeu haters e fãs.",
  "Vou contar algo que nunca contei publicamente.",
  "Esta é a verdade que ninguém quer ouvir.",
  "O LinkedIn não quer que você saiba disso.",
  "Isso vai irritar muita gente.",
  "A mentira que contamos para nós mesmos.",
  "Por que eu estava completamente errado.",
  "O post mais honesto que já escrevi.",
  "Vou ser brutalmente honesto aqui.",
  "Isso pode arruinar algumas amizades.",
  "A confissão que me libertou.",
  "O que acontece quando você fala a verdade.",
  "Isso vai contra o senso comum.",
  "A opinião impopular que defendo.",
  "Por que parei de seguir a maioria.",
  "Isso me custou seguidores, mas não me arrependo.",
  "A decisão que todos criticaram.",
  "O momento de vulnerabilidade que mudou tudo.",
  "Por que o sucesso não é o que parece.",
  "A conversa difícil que precisamos ter.",
  "Isso pode chocar você.",
  "O lado obscuro de {X}.",
  "Por que o conselho popular está errado.",
  "A história que nunca conto em entrevistas.",
  "Isso é constrangedor, mas real.",
  "O fracasso que me tornou quem sou.",
  "Por que precisamos falar sobre {X}.",
  "Isso não é motivacional. É real.",
  "A crise que me fez crescer.",
  "Por que o caminho fácil é uma armadilha.",
  "O que escondemos atrás do sucesso.",
  "Isso vai parecer arrogante, mas é a verdade.",
  "A rejeição que me impulsionou.",
  "Por que o perfeccionismo é o inimigo.",
  "O erro que repeti por anos.",
  "Isso me fez perder noites de sono.",
  "A lição mais dolorosa da minha vida.",
  "Por que precisamos normalizar o fracasso.",
  "O momento que quase desisti.",
  "Isso vai incomodar quem vive de aparências.",
  "A verdade sobre a cultura do hustle.",
  "Por que sou contra {X}.",
  "O dia que percebi que estava errado.",
  "Isso vai dividir opiniões.",
  "A crítica mais dura que já recebi.",
  "Por que a transparência é minha arma.",
  "O medo que me paralisou por anos.",
];

export const CTA_TEMPLATES = [
  "Concorda? Deixe seu comentário abaixo.",
  "Qual desses pontos mais te impactou?",
  "Salve este post para consultar depois.",
  "Marque alguém que precisa ver isso.",
  "Compartilhe com quem está passando por isso.",
  "O que você faria diferente?",
  "Me conta sua experiência nos comentários.",
  "Curta se você se identificou.",
  "Qual é o maior desafio para você nessa área?",
  "Discorda de algo? Adoraria saber sua opinião.",
  "Você já passou por algo parecido?",
  "Qual foi a maior lição que você tirou?",
  "Quer que eu aprofunde algum ponto?",
  "Reposta para ajudar mais pessoas.",
  "O que você acrescentaria a essa lista?",
  "Me segue para mais conteúdo como esse.",
  "Deixe um emoji se você concorda.",
  "Qual dica você vai implementar primeiro?",
  "Comente sua maior dúvida sobre o tema.",
  "Já viveu algo assim? Conta aqui.",
  "O que você mudaria nessa abordagem?",
  "Quer saber mais sobre esse assunto?",
  "Qual parte mais te surpreendeu?",
  "Me conta o que você pensa sobre isso.",
  "Você concorda ou discorda?",
  "Qual é o seu maior aprendizado sobre isso?",
  "O que impede você de fazer isso?",
  "Quer um post mais detalhado sobre isso?",
  "Qual foi seu maior erro nessa área?",
  "Comenta sua opinião sincera.",
  "Você aplicaria isso na sua carreira?",
  "Qual desses passos você já aplica?",
  "O que você gostaria de saber mais?",
  "Me conta sua história nos comentários.",
  "Qual foi o insight mais valioso para você?",
  "Você tem alguma dica para adicionar?",
  "Qual é o próximo passo para você?",
  "Curte e salva para não esquecer.",
  "O que você faz diferente?",
  "Compartilha com quem precisa ouvir isso.",
  "Qual foi a parte mais relevante para você?",
  "Me siga para mais posts como esse.",
  "Deixa nos comentários sua experiência.",
  "Você já tentou fazer isso?",
  "O que te impede de começar?",
  "Comente sua maior vitória nessa área.",
  "Quer que eu faça um post sobre {X}?",
  "Me manda mensagem se quiser saber mais.",
  "Salve para aplicar essa semana.",
  "Qual dica você vai testar primeiro?",
  "Discorda? Me convença nos comentários.",
  "O que você aprendeu com isso?",
  "Qual é sua opinião sobre esse tema?",
  "Já implementou algo parecido?",
  "Conta aqui o que funcionou para você.",
  "Qual foi a maior mudança que você fez?",
  "Você recomendaria isso para alguém?",
  "O que você achou desse conteúdo?",
  "Qual foi a maior revelação para você?",
  "Comente se você quer mais conteúdo assim.",
  "Qual é o seu maior obstáculo agora?",
  "Me segue para continuar essa conversa.",
  "O que você faria no meu lugar?",
  "Qual estratégia você usa?",
  "Quer um passo a passo detalhado?",
  "Comenta qual ponto mais te ajudou.",
  "Você concorda com essa visão?",
  "O que você mudaria nesse processo?",
  "Qual é sua experiência com isso?",
  "Salve e compartilhe com seu time.",
  "O que você acrescentaria aqui?",
  "Qual foi a lição mais importante?",
  "Você faria diferente?",
  "Me conta seu maior desafio.",
  "Quer mais posts sobre esse tema?",
  "Comente se isso te ajudou.",
  "Qual é o próximo passo lógico?",
  "Você recomenda algum recurso sobre isso?",
  "O que você tira como aprendizado?",
  "Compartilha sua perspectiva.",
  "Qual desses pontos você mais pratica?",
  "Me manda DM para trocar ideias.",
  "O que você gostou mais?",
  "Comente sua estratégia.",
  "Você se identifica com isso?",
  "Qual é seu conselho sobre o tema?",
  "Salve para revisar quando precisar.",
  "Conta aqui sua visão.",
  "O que você faz para melhorar nisso?",
  "Curte se concorda, comenta se discorda.",
  "Qual foi seu momento de virada?",
  "Quer que eu explore mais esse assunto?",
  "Comente uma palavra que resume sua reação.",
  "O que você aprendeu com seus erros?",
  "Qual parte você vai aplicar hoje?",
  "Me conta o que achou sinceramente.",
  "Você tem alguma dúvida sobre isso?",
  "Compartilha com alguém que vai gostar.",
  "O que você recomendaria para iniciantes?",
  "Comente seu maior aprendizado do ano.",
  "Qual é o próximo tema que você quer ver?",
  "Me segue para mais insights como esse.",
  "Deixa sua opinião nos comentários.",
];

export function getRandomHooks(count: number = 10): string[] {
  const shuffled = [...INTRO_HOOKS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getRandomViralHooks(count: number = 5): string[] {
  const shuffled = [...VIRAL_HOOKS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getRandomCTAs(count: number = 10): string[] {
  const shuffled = [...CTA_TEMPLATES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function buildContentLibraryContext(): string {
  const introHooks = getRandomHooks(15);
  const viralHooks = getRandomViralHooks(8);
  const ctas = getRandomCTAs(15);

  return `
BIBLIOTECA DE REFERÊNCIA (Use como inspiração, não copie literalmente):

HOOKS DE ABERTURA EFICAZES:
${introHooks.map((h, i) => `${i + 1}. "${h}"`).join("\n")}

HOOKS VIRAIS (para posts polêmicos/emocionais):
${viralHooks.map((h, i) => `${i + 1}. "${h}"`).join("\n")}

CTAs QUE FUNCIONAM:
${ctas.map((c, i) => `${i + 1}. "${c}"`).join("\n")}
`;
}
